### ISSUE TITLE
Add fullscreen flag to cli

### ISSUE THREAD

**Issue by kgrzywocz** [foresterre/miniview#5]
Could you add something like '--fullscreen" option?
In piston WindowSettings it's .fullscreen(true)
Also it would be great to use it as crate -> it would be easier to use it for testing ;)

Thanks in advice ;)

**Comment by foresterre** [comment]
@kgrzywocz What kind of interface would you like to see, if I were to publish it as a crate?

**Comment by kgrzywocz** [comment]
Thanks a lot!
